name: Deploy to WordPress SVN

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy plugin to WordPress.org
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@v0.0.5
        with:
          svn-username: ${{ secrets.SVN_USERNAME }}
          svn-password: ${{ secrets.SVN_PASSWORD }}
          slug: email-user-cleaner
          assets-dir: assets/
