name: Deploy to WordPress SVN

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy plugin to WordPress.org
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@v0.0.5
        with:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: email-user-cleaner
          ASSETS_DIR: assets/
